"""Static NLLB-200 translation catalog: language codes, UI names, model list.

Pure data + lookups shared by the translation routes and the live pipeline.
Extracted from speech_to_text.py so it can be imported and unit-tested without
the monolith's import-time side effects. Stdlib-only; no config needed.
"""

from __future__ import annotations

from typing import Any, Dict, List, Mapping, Optional, Tuple

# UI short code -> NLLB FLORES-200 code, for the full 202-language FLORES set.
# "auto"/unknown fall back to English. Codes with multiple scripts are keyed
# with a script suffix (e.g. "zho-Hant", "ace-Arab"); the rest keep their short
# ISO code. Serves as the target allow-list when the NLLB engine is active.
NLLB_LANG_CODES: Dict[str, str] = {
    "auto": "eng_Latn",
    "ace-Arab": "ace_Arab",
    "ace-Latn": "ace_Latn",
    "acm": "acm_Arab",
    "acq": "acq_Arab",
    "aeb": "aeb_Arab",
    "af": "afr_Latn",
    "ajp": "ajp_Arab",
    "ak": "aka_Latn",
    "als": "als_Latn",
    "am": "amh_Ethi",
    "apc": "apc_Arab",
    "ar": "arb_Arab",
    "ars": "ars_Arab",
    "ary": "ary_Arab",
    "arz": "arz_Arab",
    "as": "asm_Beng",
    "ast": "ast_Latn",
    "awa": "awa_Deva",
    "ayr": "ayr_Latn",
    "azb": "azb_Arab",
    "azj": "azj_Latn",
    "ba": "bak_Cyrl",
    "ban": "ban_Latn",
    "be": "bel_Cyrl",
    "bem": "bem_Latn",
    "bg": "bul_Cyrl",
    "bho": "bho_Deva",
    "bjn-Arab": "bjn_Arab",
    "bjn-Latn": "bjn_Latn",
    "bm": "bam_Latn",
    "bn": "ben_Beng",
    "bo": "bod_Tibt",
    "bs": "bos_Latn",
    "bug": "bug_Latn",
    "ca": "cat_Latn",
    "ceb": "ceb_Latn",
    "cjk": "cjk_Latn",
    "ckb": "ckb_Arab",
    "crh": "crh_Latn",
    "cs": "ces_Latn",
    "cy": "cym_Latn",
    "da": "dan_Latn",
    "de": "deu_Latn",
    "dik": "dik_Latn",
    "dyu": "dyu_Latn",
    "dz": "dzo_Tibt",
    "ee": "ewe_Latn",
    "el": "ell_Grek",
    "en": "eng_Latn",
    "eo": "epo_Latn",
    "es": "spa_Latn",
    "et": "est_Latn",
    "eu": "eus_Latn",
    "fa": "pes_Arab",
    "fi": "fin_Latn",
    "fil": "tgl_Latn",
    "fj": "fij_Latn",
    "fo": "fao_Latn",
    "fon": "fon_Latn",
    "fr": "fra_Latn",
    "fur": "fur_Latn",
    "fuv": "fuv_Latn",
    "ga": "gle_Latn",
    "gaz": "gaz_Latn",
    "gd": "gla_Latn",
    "gl": "glg_Latn",
    "gn": "grn_Latn",
    "gu": "guj_Gujr",
    "ha": "hau_Latn",
    "he": "heb_Hebr",
    "hi": "hin_Deva",
    "hne": "hne_Deva",
    "hr": "hrv_Latn",
    "ht": "hat_Latn",
    "hu": "hun_Latn",
    "hy": "hye_Armn",
    "id": "ind_Latn",
    "ig": "ibo_Latn",
    "ilo": "ilo_Latn",
    "is": "isl_Latn",
    "it": "ita_Latn",
    "ja": "jpn_Jpan",
    "jv": "jav_Latn",
    "ka": "kat_Geor",
    "kab": "kab_Latn",
    "kac": "kac_Latn",
    "kam": "kam_Latn",
    "kbp": "kbp_Latn",
    "kea": "kea_Latn",
    "kg": "kon_Latn",
    "khk": "khk_Cyrl",
    "ki": "kik_Latn",
    "kk": "kaz_Cyrl",
    "km": "khm_Khmr",
    "kmb": "kmb_Latn",
    "kmr": "kmr_Latn",
    "kn": "kan_Knda",
    "knc-Arab": "knc_Arab",
    "knc-Latn": "knc_Latn",
    "ko": "kor_Hang",
    "ks-Arab": "kas_Arab",
    "ks-Deva": "kas_Deva",
    "ky": "kir_Cyrl",
    "lb": "ltz_Latn",
    "lg": "lug_Latn",
    "li": "lim_Latn",
    "lij": "lij_Latn",
    "lmo": "lmo_Latn",
    "ln": "lin_Latn",
    "lo": "lao_Laoo",
    "lt": "lit_Latn",
    "ltg": "ltg_Latn",
    "lua": "lua_Latn",
    "luo": "luo_Latn",
    "lus": "lus_Latn",
    "lv": "lvs_Latn",
    "mag": "mag_Deva",
    "mai": "mai_Deva",
    "mi": "mri_Latn",
    "min": "min_Latn",
    "mk": "mkd_Cyrl",
    "ml": "mal_Mlym",
    "mni": "mni_Beng",
    "mos": "mos_Latn",
    "mr": "mar_Deva",
    "ms": "zsm_Latn",
    "mt": "mlt_Latn",
    "my": "mya_Mymr",
    "nl": "nld_Latn",
    "nn": "nno_Latn",
    "no": "nob_Latn",
    "npi": "npi_Deva",
    "nso": "nso_Latn",
    "nus": "nus_Latn",
    "ny": "nya_Latn",
    "oc": "oci_Latn",
    "ory": "ory_Orya",
    "pa": "pan_Guru",
    "pag": "pag_Latn",
    "pap": "pap_Latn",
    "pbt": "pbt_Arab",
    "pl": "pol_Latn",
    "plt": "plt_Latn",
    "prs-Arab": "prs_Arab",
    "pt": "por_Latn",
    "quy": "quy_Latn",
    "rn": "run_Latn",
    "ro": "ron_Latn",
    "ru": "rus_Cyrl",
    "rw": "kin_Latn",
    "sa": "san_Deva",
    "sat": "sat_Beng",
    "sc": "srd_Latn",
    "scn": "scn_Latn",
    "sd": "snd_Arab",
    "sg": "sag_Latn",
    "shn": "shn_Mymr",
    "si": "sin_Sinh",
    "sk": "slk_Latn",
    "sl": "slv_Latn",
    "sm": "smo_Latn",
    "sn": "sna_Latn",
    "so": "som_Latn",
    "sr": "srp_Cyrl",
    "ss": "ssw_Latn",
    "st": "sot_Latn",
    "su": "sun_Latn",
    "sv": "swe_Latn",
    "swh": "swh_Latn",
    "szl": "szl_Latn",
    "ta": "tam_Taml",
    "taq-Latn": "taq_Latn",
    "taq-Tfng": "taq_Tfng",
    "te": "tel_Telu",
    "tg": "tgk_Cyrl",
    "th": "tha_Thai",
    "ti": "tir_Ethi",
    "tk": "tuk_Latn",
    "tn": "tsn_Latn",
    "tpi": "tpi_Latn",
    "tr": "tur_Latn",
    "ts": "tso_Latn",
    "tt": "tat_Cyrl",
    "tum": "tum_Latn",
    "tw": "twi_Latn",
    "tzm": "tzm_Tfng",
    "ug": "uig_Arab",
    "uk": "ukr_Cyrl",
    "umb": "umb_Latn",
    "ur": "urd_Arab",
    "uzn": "uzn_Latn",
    "vec": "vec_Latn",
    "vi": "vie_Latn",
    "war": "war_Latn",
    "wo": "wol_Latn",
    "xh": "xho_Latn",
    "ydd": "ydd_Hebr",
    "yo": "yor_Latn",
    "yue": "yue_Hant",
    "zh": "zho_Hans",
    "zho-Hant": "zho_Hant",
    "zu": "zul_Latn",
}

# Human-readable language names for UI, keyed by UI short code. This is the
# UNION of every code across both engines (NLLB + MADLAD), so every entry in
# NLLB_LANG_CODES and MADLAD_LANG_CODES has a name here. languages_for_method()
# slices it per engine for the model-aware picker.
TRANSLATION_LANGUAGES: Dict[str, str] = {
    "aa": "Afar",
    "abt": "Ambulas",
    "ace": "Acehnese",
    "ace-Arab": "Acehnese (Arabic)",
    "ace-Latn": "Acehnese (Latin)",
    "acf": "Saint Lucian Creole French",
    "ach": "Acoli",
    "acm": "Mesopotamian Arabic",
    "acq": "Ta'izzi-Adeni Arabic",
    "ada": "Adangme",
    "adh": "Adhola",
    "ady": "Adyghe",
    "aeb": "Tunisian Arabic",
    "af": "Afrikaans",
    "agr": "Aguaruna",
    "ahk": "Akha",
    "ajp": "South Levantine Arabic",
    "ak": "Akan",
    "akb": "Batak Angkola",
    "als": "Tosk Albanian",
    "alt": "Southern Altai",
    "alz": "Alur",
    "am": "Amharic",
    "amu": "Guerrero Amuzgo",
    "ang": "Old English",
    "ann": "Obolo",
    "apc": "North Levantine Arabic",
    "ape": "Bukiyip",
    "ar": "Arabic",
    "arn": "Mapuche",
    "ars": "Najdi Arabic",
    "ary": "Moroccan Arabic",
    "arz": "Egyptian Arabic",
    "as": "Assamese",
    "ast": "Asturian",
    "av": "Avaric",
    "awa": "Awadhi",
    "ay": "Aymara",
    "ayr": "Central Aymara",
    "az": "Azerbaijani",
    "azb": "South Azerbaijani",
    "azj": "North Azerbaijani",
    "ba": "Bashkir",
    "ban": "Balinese",
    "bas": "Basaa",
    "bbc": "Batak Toba",
    "bci": "Baoulé",
    "be": "Belarusian",
    "bem": "Bemba",
    "ber": "Berber languages",
    "bew": "Betawi",
    "bg": "Bulgarian",
    "bgp": "Eastern Balochi",
    "bgz": "Banggai",
    "bho": "Bhojpuri",
    "bi": "Bislama",
    "bik": "Bikol",
    "bim": "Bimoba",
    "bjj": "Kanauji",
    "bjn-Arab": "Banjar (Arabic)",
    "bjn-Latn": "Banjar (Latin)",
    "bm": "Bambara",
    "bn": "Bengali",
    "bo": "Tibetan",
    "bqc": "Boko (Benin)",
    "br": "Breton",
    "bru": "Eastern Bru",
    "brx": "Bodo",
    "bs": "Bosnian",
    "bts": "Batak Simalungun",
    "btx": "Batak Karo",
    "bua": "Buriat",
    "bug": "Buginese",
    "bum": "Bulu",
    "bus": "Bokobaru",
    "bzj": "Belize Kriol English",
    "ca": "Catalan",
    "cab": "Garifuna",
    "cac": "Chuj",
    "cak": "Kaqchikel",
    "cbk": "Chavacano",
    "cce": "Chopi",
    "ce": "Chechen",
    "ceb": "Cebuano",
    "cfm": "Falam Chin",
    "ch": "Chamorro",
    "chk": "Chuukese",
    "chm": "Mari",
    "chr": "Cherokee",
    "cjk": "Chokwe",
    "ckb": "Central Kurdish",
    "cnh": "Hakha Chin",
    "cni": "Asháninka",
    "co": "Corsican",
    "crh": "Crimean Tatar",
    "crs": "Seselwa Creole French",
    "cs": "Czech",
    "ctu": "Chol",
    "cuk": "San Blas Kuna",
    "cv": "Chuvash",
    "cy": "Welsh",
    "da": "Danish",
    "de": "German",
    "dik": "Southwestern Dinka",
    "din": "Dinka",
    "dje": "Zarma",
    "djk": "Eastern Maroon Creole",
    "dov": "Dombe",
    "dtp": "Central Dusun",
    "dv": "Divehi",
    "dwr": "Dawro",
    "dyu": "Dyula",
    "dz": "Dzongkha",
    "ee": "Ewe",
    "el": "Greek",
    "emp": "Northern Emberá",
    "en": "English",
    "enq": "Enga",
    "eo": "Esperanto",
    "es": "Spanish",
    "et": "Estonian",
    "eu": "Basque",
    "fa": "Persian",
    "ff": "Fula",
    "ffm": "Maasina Fulfulde",
    "fi": "Finnish",
    "fil": "Filipino",
    "fip": "Fipa",
    "fj": "Fijian",
    "fo": "Faroese",
    "fon": "Fon",
    "fr": "French",
    "frp": "Arpitan",
    "fur": "Friulian",
    "fuv": "Nigerian Fulfulde",
    "fy": "Western Frisian",
    "ga": "Irish",
    "gag": "Gagauz",
    "gaz": "West Central Oromo",
    "gbm": "Garhwali",
    "gd": "Scottish Gaelic",
    "gil": "Gilbertese",
    "gl": "Galician",
    "gn": "Guarani",
    "gof": "Gofa",
    "gom": "Goan Konkani",
    "gor": "Gorontalo",
    "grc": "Ancient Greek",
    "gsw": "Swiss German",
    "gu": "Gujarati",
    "gub": "Guajajára",
    "guc": "Wayuu",
    "guh": "Guahibo",
    "gui": "Eastern Bolivian Guaraní",
    "gv": "Manx",
    "gvl": "Gulay",
    "gym": "Ngäbere",
    "gyn": "Guyanese Creole English",
    "ha": "Hausa",
    "haw": "Hawaiian",
    "he": "Hebrew",
    "hi": "Hindi",
    "hif": "Fiji Hindi",
    "hil": "Hiligaynon",
    "hmn": "Hmong",
    "hne": "Chhattisgarhi",
    "ho": "Hiri Motu",
    "hr": "Croatian",
    "ht": "Haitian Creole",
    "hu": "Hungarian",
    "hui": "Huli",
    "hus": "Huastec",
    "hvn": "Sabu",
    "hy": "Armenian",
    "iba": "Iban",
    "ibb": "Ibibio",
    "id": "Indonesian",
    "ify": "Keley-I Kallahan",
    "ig": "Igbo",
    "ilo": "Iloko",
    "inb": "Inga",
    "is": "Icelandic",
    "iso": "Isoko",
    "it": "Italian",
    "iu": "Inuktitut",
    "ium": "Iu Mien",
    "izz": "Izii",
    "ja": "Japanese",
    "jac": "Popti'",
    "jam": "Jamaican Creole English",
    "jax": "Jambi Malay",
    "jiv": "Shuar",
    "jv": "Javanese",
    "jvn": "Caribbean Javanese",
    "ka": "Georgian",
    "kaa": "Kara-Kalpak",
    "kab": "Kabyle",
    "kac": "Kachin",
    "kam": "Kamba",
    "kbd": "Kabardian",
    "kbp": "Kabiyè",
    "kea": "Kabuverdianu",
    "kek": "Kekchí",
    "kg": "Kongo",
    "kha": "Khasi",
    "khk": "Halh Mongolian",
    "ki": "Kikuyu",
    "kj": "Kuanyama",
    "kjg": "Khmu",
    "kjh": "Khakas",
    "kk": "Kazakh",
    "kl": "Kalaallisut",
    "km": "Khmer",
    "kmb": "Kimbundu",
    "kmr": "Northern Kurdish",
    "kn": "Kannada",
    "knc-Arab": "Central Kanuri (Arabic)",
    "knc-Latn": "Central Kanuri (Latin)",
    "knj": "Western Kanjobal",
    "ko": "Korean",
    "koi": "Komi-Permyak",
    "kos": "Kosraean",
    "krc": "Karachay-Balkar",
    "kri": "Krio",
    "krj": "Kinaray-a",
    "ks": "Kashmiri",
    "ks-Arab": "Kashmiri (Arabic)",
    "ks-Deva": "Kashmiri (Devanagari)",
    "ksd": "Kuanua",
    "ksw": "S'gaw Karen",
    "ktu": "Kituba (Democratic Republic of Congo)",
    "ku": "Kurdish",
    "kum": "Kumyk",
    "kv": "Komi",
    "kw": "Cornish",
    "kwi": "Awa-Cuaiquer",
    "ky": "Kyrgyz",
    "la": "Latin",
    "laj": "Lango (Uganda)",
    "lb": "Luxembourgish",
    "lg": "Ganda",
    "lhu": "Lahu",
    "li": "Limburgish",
    "lij": "Ligurian",
    "lmo": "Lombard",
    "ln": "Lingala",
    "lo": "Lao",
    "lrc": "Northern Luri",
    "lt": "Lithuanian",
    "ltg": "Latgalian",
    "lu": "Luba-Katanga",
    "lua": "Luba-Lulua",
    "luo": "Luo (Kenya and Tanzania)",
    "lus": "Mizo",
    "luz": "Southern Luri",
    "lv": "Latvian",
    "mad": "Madurese",
    "mag": "Magahi",
    "mai": "Maithili",
    "mak": "Makasar",
    "mam": "Mam",
    "mas": "Masai",
    "maz": "Central Mazahua",
    "mbt": "Matigsalug Manobo",
    "mdf": "Moksha",
    "mel": "Central Melanau",
    "meo": "Kedah Malay",
    "meu": "Motu",
    "mey": "Hassaniyya",
    "mfe": "Morisyen",
    "mg": "Malagasy",
    "mgh": "Makhuwa-Meetto",
    "mh": "Marshallese",
    "mi": "Māori",
    "min": "Minangkabau",
    "miq": "Mískito",
    "mk": "Macedonian",
    "mkn": "Kupang Malay",
    "ml": "Malayalam",
    "mn": "Mongolian",
    "mni": "Manipuri",
    "mnw": "Mon",
    "mos": "Mossi",
    "mps": "Dadibi",
    "mqy": "Manggarai",
    "mr": "Marathi",
    "mrj": "Western Mari",
    "mrw": "Maranao",
    "ms": "Malay",
    "msb": "Masbatenyo",
    "msi": "Sabah Malay",
    "msm": "Agusan Manobo",
    "mt": "Maltese",
    "mtr": "Mewari",
    "my": "Burmese",
    "myv": "Erzya",
    "ne": "Nepali",
    "new": "Newari",
    "ngu": "Guerrero Nahuatl",
    "nhe": "Eastern Huasteca Nahuatl",
    "nia": "Nias",
    "nij": "Ngaju",
    "niq": "Nandi",
    "nl": "Dutch",
    "nn": "Norwegian Nynorsk",
    "nnb": "Nande",
    "no": "Norwegian",
    "noa": "Woun Meu",
    "noe": "Nimadi",
    "nog": "Nogai",
    "npi": "Nepali (individual language)",
    "nr": "South Ndebele",
    "nso": "Northern Sotho",
    "nus": "Nuer",
    "nut": "Nung (Viet Nam)",
    "nv": "Navajo",
    "ny": "Nyanja",
    "nyu": "Nyungwe",
    "nzi": "Nzima",
    "oc": "Occitan",
    "oj": "Ojibwa",
    "om": "Oromo",
    "or": "Odia",
    "ory": "Odia (individual language)",
    "os": "Ossetic",
    "otq": "Querétaro Otomi",
    "pa": "Punjabi",
    "pag": "Pangasinan",
    "pam": "Pampanga",
    "pap": "Papiamento",
    "pau": "Palauan",
    "pbt": "Southern Pashto",
    "pck": "Paite Chin",
    "pis": "Pijin",
    "pl": "Polish",
    "plt": "Plateau Malagasy",
    "pon": "Pohnpeian",
    "ppk": "Uma",
    "prk": "Parauk",
    "prs-Arab": "Persian (Afghanistan)",
    "ps": "Pashto",
    "pt": "Portuguese",
    "qu": "Quechua",
    "qub": "Huallaga Huánuco Quechua",
    "quc": "Kʼicheʼ",
    "quf": "Lambayeque Quechua",
    "quh": "South Bolivian Quechua",
    "qup": "Southern Pastaza Quechua",
    "quy": "Ayacucho Quechua",
    "qvc": "Cajamarca Quechua",
    "qvi": "Imbabura Highland Quichua",
    "qvz": "Northern Pastaza Quichua",
    "qxr": "Cañar Highland Quichua",
    "raj": "Rajasthani",
    "rcf": "Réunion Creole French",
    "rki": "Rakhine",
    "rm": "Romansh",
    "rmc": "Carpathian Romani",
    "rn": "Rundi",
    "ro": "Romanian",
    "rom": "Romany",
    "ru": "Russian",
    "rw": "Kinyarwanda",
    "rwo": "Rawa",
    "sa": "Sanskrit",
    "sah": "Yakut",
    "sat": "Santali",
    "sc": "Sardinian",
    "scn": "Sicilian",
    "sd": "Sindhi",
    "sda": "Toraja-Sa'dan",
    "se": "Northern Sami",
    "seh": "Sena",
    "sg": "Sango",
    "shn": "Shan",
    "shp": "Shipibo-Conibo",
    "si": "Sinhala",
    "sja": "Epena",
    "sjp": "Surjapuri",
    "sk": "Slovak",
    "skr": "Saraiki",
    "sl": "Slovenian",
    "sm": "Samoan",
    "smt": "Simte",
    "sn": "Shona",
    "so": "Somali",
    "spp": "Supyire Senoufo",
    "sq": "Albanian",
    "sr": "Serbian",
    "srm": "Saramaccan",
    "srn": "Sranan Tongo",
    "srr": "Serer",
    "ss": "Swati",
    "st": "Southern Sotho",
    "stq": "Saterland Frisian",
    "su": "Sundanese",
    "sus": "Susu",
    "suz": "Sunwar",
    "sv": "Swedish",
    "sw": "Swahili",
    "swh": "Swahili (individual language)",
    "sxn": "Sangir",
    "syl": "Sylheti",
    "syr": "Syriac",
    "szl": "Silesian",
    "ta": "Tamil",
    "tab": "Tabassaran",
    "taj": "Eastern Tamang",
    "taq-Latn": "Tamasheq (Latin)",
    "taq-Tfng": "Tamasheq (Tifinagh)",
    "tbz": "Ditammari",
    "tca": "Ticuna",
    "tcy": "Tulu",
    "tdx": "Tandroy-Mahafaly Malagasy",
    "te": "Telugu",
    "teo": "Teso",
    "tet": "Tetum",
    "tg": "Tajik",
    "th": "Thai",
    "ti": "Tigrinya",
    "tiv": "Tiv",
    "tk": "Turkmen",
    "tks": "Takestani",
    "tll": "Tetela",
    "tn": "Tswana",
    "to": "Tongan",
    "toj": "Tojolabal",
    "tpi": "Tok Pisin",
    "tr": "Turkish",
    "trp": "Kok Borok",
    "ts": "Tsonga",
    "tsc": "Tswa",
    "tsg": "Tausug",
    "tt": "Tatar",
    "tuc": "Mutu",
    "tum": "Tumbuka",
    "tvl": "Tuvalu",
    "tw": "Twi",
    "twu": "Termanu",
    "tyv": "Tuvinian",
    "tyz": "Tày",
    "tzh": "Tzeltal",
    "tzj": "Tz'utujil",
    "tzm": "Central Atlas Tamazight",
    "tzo": "Tzotzil",
    "ubu": "Umbu-Ungu",
    "udm": "Udmurt",
    "ug": "Uyghur",
    "uk": "Ukrainian",
    "umb": "Umbundu",
    "ur": "Urdu",
    "uz": "Uzbek",
    "uzn": "Northern Uzbek",
    "ve": "Venda",
    "vec": "Venetian",
    "vi": "Vietnamese",
    "wa": "Walloon",
    "wal": "Wolaytta",
    "war": "Waray",
    "wo": "Wolof",
    "xal": "Kalmyk",
    "xh": "Xhosa",
    "xmm": "Manado Malay",
    "yap": "Yapese",
    "ydd": "Eastern Yiddish",
    "yi": "Yiddish",
    "yo": "Yoruba",
    "yua": "Yucateco",
    "yue": "Cantonese",
    "za": "Zhuang",
    "zap": "Zapotec",
    "zh": "Chinese (Simplified)",
    "zho-Hant": "Chinese (Traditional)",
    "zne": "Zande (individual language)",
    "zu": "Zulu",
    "zza": "Zaza",
}

_NLLB_MODEL_DESCRIPTIONS: Dict[str, str] = {
    "facebook/nllb-200-distilled-600M": "Distilled 600M - Fast, good quality. Recommended for most users.",
    "facebook/nllb-200-distilled-1.3B": "Distilled 1.3B - Better quality, moderate speed.",
    "facebook/nllb-200-1.3B": "Full 1.3B - High quality, slower.",
    "facebook/nllb-200-3.3B": "Full 3.3B - Best quality, requires significant VRAM.",
    "facebook/nllb-moe-54b": "MoE 54B - Mixture of Experts, requires 80GB+ VRAM.",
}


def get_nllb_model_description(model_id: str) -> str:
    """Human-readable blurb for a known NLLB model id, or a generic fallback."""
    return _NLLB_MODEL_DESCRIPTIONS.get(
        model_id, "NLLB translation model - 200+ languages supported")


def get_default_nllb_models() -> List[Dict[str, Any]]:
    """The known NLLB models, used when the HuggingFace API is unreachable.

    Shape matches the entries the /api/models/nllb-list route builds from the
    HF API (model_id, name, size, size_order, downloads, likes, description).
    """
    return [
        {
            "model_id": "facebook/nllb-200-distilled-600M",
            "name": "nllb-200-distilled-600M",
            "size": "~1.2 GB",
            "size_order": 1,
            "downloads": 0,
            "likes": 0,
            "description": "Distilled 600M - Fast, good quality. Recommended for most users."
        },
        {
            "model_id": "facebook/nllb-200-distilled-1.3B",
            "name": "nllb-200-distilled-1.3B",
            "size": "~2.6 GB",
            "size_order": 2,
            "downloads": 0,
            "likes": 0,
            "description": "Distilled 1.3B - Better quality, moderate speed."
        },
        {
            "model_id": "facebook/nllb-200-1.3B",
            "name": "nllb-200-1.3B",
            "size": "~5.2 GB",
            "size_order": 3,
            "downloads": 0,
            "likes": 0,
            "description": "Full 1.3B - High quality, slower."
        },
        {
            "model_id": "facebook/nllb-200-3.3B",
            "name": "nllb-200-3.3B",
            "size": "~13 GB",
            "size_order": 4,
            "downloads": 0,
            "likes": 0,
            "description": "Full 3.3B - Best quality, requires significant VRAM."
        }
    ]


# --- LLM translation ---------------------------------------------------------
# An LLM has no target-language token table, so unlike NLLB and MADLAD its
# supported set is not a property of the model file — it is a judgement about
# where a small quantised instruction model produces captions good enough to put
# in front of a congregation. Offering the NLLB or MADLAD list here would promise
# hundreds of low-resource languages that such a model translates badly, and a
# bad caption is worse than no caption.
#
# So this is a deliberately short, high-resource set. The value is the language's
# English name, which is what actually reaches the model (see
# stt/llm_translate.py:build_system_prompt) rather than a code the model has
# never been trained to interpret. Adding a language here is a one-line change
# once someone has checked the output is usable.
LLM_LANG_CODES: Dict[str, str] = {
    "auto": "English",
    # Western Europe
    "en": "English",
    "es": "Spanish",
    "fr": "French",
    "de": "German",
    "it": "Italian",
    "pt": "Portuguese",
    "nl": "Dutch",
    # Nordic
    "sv": "Swedish",
    "da": "Danish",
    "no": "Norwegian",
    "fi": "Finnish",
    # Central and Eastern Europe — the languages this project is actually
    # deployed into alongside Russian.
    "pl": "Polish",
    "cs": "Czech",
    "uk": "Ukrainian",
    "ru": "Russian",
    "ro": "Romanian",
    "hu": "Hungarian",
    "bg": "Bulgarian",
    "sr": "Serbian",
    "el": "Greek",
    # Other high-resource languages
    "tr": "Turkish",
    "ar": "Arabic",
    "he": "Hebrew",
    "zh": "Chinese (Simplified)",
    "ja": "Japanese",
    "ko": "Korean",
    "vi": "Vietnamese",
    "id": "Indonesian",
    "hi": "Hindi",
}


# --- MADLAD-400 (Google) -----------------------------------------------------
# MADLAD is a T5 MT model selected with a "<2xx>" target-language prefix on the
# input text (no source language, no forced_bos_token). Codes are short and
# mostly identical to our UI short codes; Hebrew uses Google's "iw" convention.
# "auto"/unknown fall back to English. This map also serves as the supported-
# target set for validation when the MADLAD engine is active.
MADLAD_LANG_CODES: Dict[str, str] = {
    "auto": "en",
    "aa": "aa",
    "abt": "abt",
    "ace": "ace",
    "acf": "acf",
    "ach": "ach",
    "ada": "ada",
    "adh": "adh",
    "ady": "ady",
    "af": "af",
    "agr": "agr",
    "ahk": "ahk",
    "ak": "ak",
    "akb": "akb",
    "alt": "alt",
    "alz": "alz",
    "am": "am",
    "amu": "amu",
    "ang": "ang",
    "ann": "ann",
    "ape": "ape",
    "ar": "ar",
    "arn": "arn",
    "as": "as",
    "av": "av",
    "awa": "awa",
    "ay": "ay",
    "az": "az",
    "ba": "ba",
    "ban": "ban",
    "bas": "bas",
    "bbc": "bbc",
    "bci": "bci",
    "be": "be",
    "ber": "ber",
    "bew": "bew",
    "bg": "bg",
    "bgp": "bgp",
    "bgz": "bgz",
    "bho": "bho",
    "bi": "bi",
    "bik": "bik",
    "bim": "bim",
    "bjj": "bjj",
    "bm": "bm",
    "bn": "bn",
    "bo": "bo",
    "bqc": "bqc",
    "br": "br",
    "bru": "bru",
    "brx": "brx",
    "bs": "bs",
    "bts": "bts",
    "btx": "btx",
    "bua": "bua",
    "bum": "bum",
    "bus": "bus",
    "bzj": "bzj",
    "ca": "ca",
    "cab": "cab",
    "cac": "cac",
    "cak": "cak",
    "cbk": "cbk",
    "cce": "cce",
    "ce": "ce",
    "ceb": "ceb",
    "cfm": "cfm",
    "ch": "ch",
    "chk": "chk",
    "chm": "chm",
    "chr": "chr",
    "cjk": "cjk",
    "ckb": "ckb",
    "cnh": "cnh",
    "cni": "cni",
    "co": "co",
    "crh": "crh",
    "crs": "crs",
    "cs": "cs",
    "ctu": "ctu",
    "cuk": "cuk",
    "cv": "cv",
    "cy": "cy",
    "da": "da",
    "de": "de",
    "din": "din",
    "dje": "dje",
    "djk": "djk",
    "dov": "dov",
    "dtp": "dtp",
    "dv": "dv",
    "dwr": "dwr",
    "dyu": "dyu",
    "dz": "dz",
    "ee": "ee",
    "el": "el",
    "emp": "emp",
    "en": "en",
    "enq": "enq",
    "eo": "eo",
    "es": "es",
    "et": "et",
    "eu": "eu",
    "fa": "fa",
    "ff": "ff",
    "ffm": "ffm",
    "fi": "fi",
    "fil": "fil",
    "fip": "fip",
    "fj": "fj",
    "fo": "fo",
    "fon": "fon",
    "fr": "fr",
    "frp": "frp",
    "fy": "fy",
    "ga": "ga",
    "gag": "gag",
    "gbm": "gbm",
    "gd": "gd",
    "gil": "gil",
    "gl": "gl",
    "gn": "gn",
    "gof": "gof",
    "gom": "gom",
    "gor": "gor",
    "grc": "grc",
    "gsw": "gsw",
    "gu": "gu",
    "gub": "gub",
    "guc": "guc",
    "guh": "guh",
    "gui": "gui",
    "gv": "gv",
    "gvl": "gvl",
    "gym": "gym",
    "gyn": "gyn",
    "ha": "ha",
    "haw": "haw",
    "he": "iw",
    "hi": "hi",
    "hif": "hif",
    "hil": "hil",
    "hmn": "hmn",
    "hne": "hne",
    "ho": "ho",
    "hr": "hr",
    "ht": "ht",
    "hu": "hu",
    "hui": "hui",
    "hus": "hus",
    "hvn": "hvn",
    "hy": "hy",
    "iba": "iba",
    "ibb": "ibb",
    "id": "id",
    "ify": "ify",
    "ig": "ig",
    "ilo": "ilo",
    "inb": "inb",
    "is": "is",
    "iso": "iso",
    "it": "it",
    "iu": "iu",
    "ium": "ium",
    "izz": "izz",
    "ja": "ja",
    "jac": "jac",
    "jam": "jam",
    "jax": "jax",
    "jiv": "jiv",
    "jv": "jv",
    "jvn": "jvn",
    "ka": "ka",
    "kaa": "kaa",
    "kac": "kac",
    "kbd": "kbd",
    "kbp": "kbp",
    "kek": "kek",
    "kg": "kg",
    "kha": "kha",
    "kj": "kj",
    "kjg": "kjg",
    "kjh": "kjh",
    "kk": "kk",
    "kl": "kl",
    "km": "km",
    "kmb": "kmb",
    "kn": "kn",
    "knj": "knj",
    "ko": "ko",
    "koi": "koi",
    "kos": "kos",
    "krc": "krc",
    "kri": "kri",
    "krj": "krj",
    "ks": "ks",
    "ksd": "ksd",
    "ksw": "ksw",
    "ktu": "ktu",
    "ku": "ku",
    "kum": "kum",
    "kv": "kv",
    "kw": "kw",
    "kwi": "kwi",
    "ky": "ky",
    "la": "la",
    "laj": "laj",
    "lb": "lb",
    "lg": "lg",
    "lhu": "lhu",
    "ln": "ln",
    "lo": "lo",
    "lrc": "lrc",
    "lt": "lt",
    "ltg": "ltg",
    "lu": "lu",
    "lus": "lus",
    "luz": "luz",
    "lv": "lv",
    "mad": "mad",
    "mag": "mag",
    "mai": "mai",
    "mak": "mak",
    "mam": "mam",
    "mas": "mas",
    "maz": "maz",
    "mbt": "mbt",
    "mdf": "mdf",
    "mel": "mel",
    "meo": "meo",
    "meu": "meu",
    "mey": "mey",
    "mfe": "mfe",
    "mg": "mg",
    "mgh": "mgh",
    "mh": "mh",
    "mi": "mi",
    "min": "min",
    "miq": "miq",
    "mk": "mk",
    "mkn": "mkn",
    "ml": "ml",
    "mn": "mn",
    "mni": "mni",
    "mnw": "mnw",
    "mps": "mps",
    "mqy": "mqy",
    "mr": "mr",
    "mrj": "mrj",
    "mrw": "mrw",
    "ms": "ms",
    "msb": "msb",
    "msi": "msi",
    "msm": "msm",
    "mt": "mt",
    "mtr": "mtr",
    "my": "my",
    "myv": "myv",
    "ne": "ne",
    "new": "new",
    "ngu": "ngu",
    "nhe": "nhe",
    "nia": "nia",
    "nij": "nij",
    "niq": "niq",
    "nl": "nl",
    "nnb": "nnb",
    "no": "no",
    "noa": "noa",
    "noe": "noe",
    "nog": "nog",
    "nr": "nr",
    "nso": "nso",
    "nut": "nut",
    "nv": "nv",
    "ny": "ny",
    "nyu": "nyu",
    "nzi": "nzi",
    "oc": "oc",
    "oj": "oj",
    "om": "om",
    "or": "or",
    "os": "os",
    "otq": "otq",
    "pa": "pa",
    "pag": "pag",
    "pam": "pam",
    "pap": "pap",
    "pau": "pau",
    "pck": "pck",
    "pis": "pis",
    "pl": "pl",
    "pon": "pon",
    "ppk": "ppk",
    "prk": "prk",
    "ps": "ps",
    "pt": "pt",
    "qu": "qu",
    "qub": "qub",
    "quc": "quc",
    "quf": "quf",
    "quh": "quh",
    "qup": "qup",
    "quy": "quy",
    "qvc": "qvc",
    "qvi": "qvi",
    "qvz": "qvz",
    "qxr": "qxr",
    "raj": "raj",
    "rcf": "rcf",
    "rki": "rki",
    "rm": "rm",
    "rmc": "rmc",
    "rn": "rn",
    "ro": "ro",
    "rom": "rom",
    "ru": "ru",
    "rw": "rw",
    "rwo": "rwo",
    "sa": "sa",
    "sah": "sah",
    "sd": "sd",
    "sda": "sda",
    "se": "se",
    "seh": "seh",
    "sg": "sg",
    "shn": "shn",
    "shp": "shp",
    "si": "si",
    "sja": "sja",
    "sjp": "sjp",
    "sk": "sk",
    "skr": "skr",
    "sl": "sl",
    "sm": "sm",
    "smt": "smt",
    "sn": "sn",
    "so": "so",
    "spp": "spp",
    "sq": "sq",
    "sr": "sr",
    "srm": "srm",
    "srn": "srn",
    "srr": "srr",
    "ss": "ss",
    "st": "st",
    "stq": "stq",
    "su": "su",
    "sus": "sus",
    "suz": "suz",
    "sv": "sv",
    "sw": "sw",
    "sxn": "sxn",
    "syl": "syl",
    "syr": "syr",
    "ta": "ta",
    "tab": "tab",
    "taj": "taj",
    "tbz": "tbz",
    "tca": "tca",
    "tcy": "tcy",
    "tdx": "tdx",
    "te": "te",
    "teo": "teo",
    "tet": "tet",
    "tg": "tg",
    "th": "th",
    "ti": "ti",
    "tiv": "tiv",
    "tk": "tk",
    "tks": "tks",
    "tll": "tll",
    "tn": "tn",
    "to": "to",
    "toj": "toj",
    "tr": "tr",
    "trp": "trp",
    "ts": "ts",
    "tsc": "tsc",
    "tsg": "tsg",
    "tt": "tt",
    "tuc": "tuc",
    "tvl": "tvl",
    "twu": "twu",
    "tyv": "tyv",
    "tyz": "tyz",
    "tzh": "tzh",
    "tzj": "tzj",
    "tzo": "tzo",
    "ubu": "ubu",
    "udm": "udm",
    "ug": "ug",
    "uk": "uk",
    "ur": "ur",
    "uz": "uz",
    "ve": "ve",
    "vec": "vec",
    "vi": "vi",
    "wa": "wa",
    "wal": "wal",
    "war": "war",
    "wo": "wo",
    "xal": "xal",
    "xh": "xh",
    "xmm": "xmm",
    "yap": "yap",
    "yi": "yi",
    "yo": "yo",
    "yua": "yua",
    "yue": "yue",
    "za": "za",
    "zap": "zap",
    "zh": "zh",
    "zne": "zne",
    "zu": "zu",
    "zza": "zza",
}


def madlad_target_code(target_lang: str) -> str:
    """UI short code -> MADLAD language code (fallback English)."""
    return MADLAD_LANG_CODES.get(target_lang, "en")


def build_madlad_input(text: str, target_lang: str) -> str:
    """MADLAD input is the text prefixed with a '<2xx>' target tag."""
    return f"<2{madlad_target_code(target_lang)}> {text}"


def is_madlad_model(model_id: str) -> bool:
    """Whether a model id refers to a MADLAD-400 model (vs NLLB)."""
    return "madlad" in (model_id or "").lower()


def resolve_translation_model_id(lt_cfg: Optional[Mapping[str, Any]], madlad_default: str) -> str:
    """Effective live-translation model id for the configured engine.

    translate_text() branches on the LOADED model, so the engine ("nllb"/
    "madlad") and the model id must agree. If the engine is 'madlad' but the
    configured model isn't a MADLAD model (e.g. a stale NLLB id), fall back to
    ``madlad_default`` so 'madlad' doesn't silently run NLLB weights.

    The monolith's _resolve_live_translation_model_id() delegates here, and
    session provenance records the result, so the recorded model is the one that
    actually ran rather than the possibly-stale configured string.
    """
    cfg = lt_cfg or {}
    method = cfg.get("translation_method", "nllb")
    model_id = cfg.get("translation_model")
    if method == "madlad" and not is_madlad_model(model_id or ""):
        return madlad_default
    return model_id or ""


def _codes_for_method(method: str) -> Dict[str, str]:
    """The UI-code table the given engine supports."""
    if method == "madlad":
        return MADLAD_LANG_CODES
    if method == "llm":
        return LLM_LANG_CODES
    return NLLB_LANG_CODES


def supported_target(lang: str, method: str) -> bool:
    """Whether a UI target-language short code is valid for the active engine."""
    return lang in _codes_for_method(method)


def languages_for_method(method: str) -> Dict[str, str]:
    """UI short code -> English name for every language the given engine supports.

    ``method`` is "madlad", "llm", or "nllb" (anything else is treated as NLLB).
    Excludes the special "auto" entry, which the UI adds separately. Used to
    drive the model-aware language picker so each engine only offers the
    languages it can actually translate to.

    The LLM gets its own short high-resource list (see LLM_LANG_CODES) rather
    than NLLB's or MADLAD's, because its coverage is a judgement about output
    quality rather than a property of a model file.
    """
    table = _codes_for_method(method)
    return {code: TRANSLATION_LANGUAGES[code]
            for code in table
            if code != "auto" and code in TRANSLATION_LANGUAGES}


def madlad_anti_repetition_defaults(repetition_penalty: float, no_repeat_ngram_size: int) -> Tuple[float, int]:
    """Anti-repetition generation params for MADLAD, which can fall into
    repetition loops. Nudges the neutral defaults to safe values but keeps any
    operator-tuned settings: repetition_penalty 1.0 -> 1.1, no_repeat 0 -> 4.
    Returns (repetition_penalty, no_repeat_ngram_size)."""
    rep = repetition_penalty if (repetition_penalty and repetition_penalty != 1.0) else 1.1
    nr = no_repeat_ngram_size if (no_repeat_ngram_size and no_repeat_ngram_size > 0) else 4
    return rep, nr


def get_default_madlad_models() -> List[Dict[str, Any]]:
    """Known MADLAD-400 models, used when the HuggingFace API is unreachable.
    Same shape as get_default_nllb_models()."""
    return [
        {
            "model_id": "google/madlad400-3b-mt",
            "name": "madlad400-3b-mt",
            "size": "~12 GB",
            "size_order": 1,
            "downloads": 0,
            "likes": 0,
            "description": "MADLAD-400 3B - 400+ languages, high quality. ~12 GB (use fp16 on GPU)."
        },
        {
            "model_id": "google/madlad400-7b-mt",
            "name": "madlad400-7b-mt",
            "size": "~27 GB",
            "size_order": 2,
            "downloads": 0,
            "likes": 0,
            "description": "MADLAD-400 7B - Best quality, requires significant VRAM."
        }
    ]
